config/routes.rb
Rails.application.routes.draw do
  root 'application#splash'
  get       '/login', to: 'sessions#new'
  post      '/login', to: 'sessions#create'
  delete    '/login', to: 'sessions#destroy', as: '/logout'
  get       '/users/graph', to: 'users#graph'
  get       '/exercises/search', to: 'exercises#search'
  get       '/contact', to: 'pages#contact'
  get       '/about', to: 'pages#about'
  resources :categories
  resources :exercises
  resources :workouts
  resources :workout_sets, only: [:new, :create, :edit, :update, :destroy]
  resources :users, only: [:new, :create, :edit, :update, :show]
  resources :profiles, only: [:show, :new, :create, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
require 'bcrypt'

class User < ApplicationRecord
  attr_accessor :graph_data
  has_one :profile
  # has_many :histories
  has_many :workouts
  has_many :workout_sets, through: :workouts

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 5}, format: { with: /[0-9!@#$%^&*\(\)\\\/\[\]]+/, message: "must include non-alphabetic characters."}

  has_secure_password

  def last_five_workouts
    sorted_workouts = self.workouts.sort_by(&:date).reverse
    workouts_with_sets = sorted_workouts.select {|w| w.workout_sets.any? }
    workouts_with_sets[0..4]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :verify_login, only: [:edit, :update, :destroy]
  before_action :set_user, only: [:edit, :show, :update, :destroy]

  def index
    @users = User.all
  end

  def edit
  end
    
  def new
    @user = User.new
  end

  def show
    @user.build_profile unless @user.profile
    @data = @user.workouts.map do |workout|
      [(workout.date.to_date - DateTime.now.to_date).to_i, workout.user_weight]
    end
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      session[:user_id] = @user.id
      redirect_to new_profile_path(@user)
    else
      flash[:error] = "Invalid Input. Please Re-enter your information."
      flash[:password] = @user.errors.full_messages_for(:password).join(". ") if @user.errors[:password]
      flash[:username] = @user.errors.full_messages_for(:username).join(". ") if @user.errors[:username]
      flash[:email] = @user.errors.full_messages_for(:email).join(". ") if @user.errors[:email]
      render :new
    end
  end

  def graph
    @user = User.find_by(id: params[:id])
    ordered_workouts = @user.workouts.sort_by(&:date).reverse
    @data = ordered_workouts[0..50].map do |workout|
      exercise_sets = workout.workout_sets.select do |set|
        set.exercise_id == params[:exercise_id].to_i
      end
      if exercise_sets.any?
        max = exercise_sets.max_by {|set| set.weight }
        [(workout.date.to_date - DateTime.now.to_date).to_i, max.weight]
      end
    end
    @data.delete_if {|v| v.nil? }
    
    render :show
  end

  def update
    @user = User.update(user_params)
    if @user.valid?
      @user.save
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation, :email)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/__new.html.erb
<% content_tag(:h2, flash[:error], class: "is-error") if flash[:error] %>

<%= form_for @user do |u| %>
  <div class="field">
    <%= content_tag(:h3, flash[:username]) if flash[:username] %>
    <%= u.label :username %>
    <%= u.text_field :username, class: "input #{"is-danger" if flash[:username]}" %>
  </div>
  <div class="field">
    <%= content_tag(:h3, flash[:email]) if flash[:email] %>
    <%= u.label :email %>
    <%= u.text_field :email, class: "input #{"is-danger" if flash[:email]}" %>
  </div>
  <div class="field">
    <%= content_tag(:h3, flash[:password]) if flash[:password] %>
    <%= u.label :password %>
    <%= u.password_field :password, class: "input #{"is-danger" if flash[:password]}" %>
  </div>
  <div class="field">
    <%= u.label :password_confirmation %>
    <%= u.password_field :password_confirmation, class: "input #{"is-danger" if flash[:password]}" %>
  </div>
  <%= u.submit 'Create User', class: "button is-primary" %>
<% end %>

<section class="field is-horizontal">
  <%= form_for @profile do |p| %>
    <%= p.hidden_field :user_id, value: @profile.user.id %>
    <div class="field is-horizontal">
      <div class="field-label is-normal">
        <%= p.label :name, class: "label" %>
      </div>
      <div class="field-body">
        <div class="field">
          <div class="control">
            <%= p.text_field :name, class: "input" %>
          </div>
        </div>
      </div>
    </div>
    <div class="field is-horizontal">
      <div class="field-label is-normal">
        <%= p.label :height, class: "label" %>
      </div>
      <div class="field-body">
        <div class="field has-addons">
          <div class="control is-expanded">
            <%= p.number_field :height, class: "input is-fullwidth" %>
          </div>
          <div class="control select">
            <%= p.select :height_unit, [['Meters', true], ['Feet', false]], {}, class: "select"%>
          </div>
        </div>
      </div>
    </div>
    <div class="field is-horizontal">
      <div class="field-label is-normal">
        <%= p.label :starting_weight, class: "label" %>
      </div>
      <div class="field-body">
        <div class="field has-addons">
          <div class="control is-expanded">
            <%= p.number_field :starting_weight, class: "input is-fullwidth" %>
          </div>
          <div class="control select">
            <%= p.select :weight_unit, [['Kg', true], ['Lbs', false]], {}, class: "select"%>
          </div>
        </div>
      </div>
    </div>
    <div class="field is-horizontal">
      <div class="field-label is-normal">
        <%= p.label :age, class: "label" %>
      </div>
      <div class="field-body">
        <div class="field">
          <div class="control is-expanded">
            <%= p.number_field :age, class: "input" %>
          </div>
        </div>
      </div>
    </div>
    <div class="field is-horizontal">
    </div>
    <div class="field is-horizontal">
      <div class="field-label is-normal">
        <%= p.label "Preferred Units:", class: "label" %>
      </div>
      <div class="field-body">
        <div class="field">
          <div class="control">
            <div class="select">
              <%= p.select :metric, [['Metric', true], ['Merican', false]], {}, class: "select"%>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="field is-horizontal">
      <div class="field-label">
        <!-- Left empty for spacing -->
      </div>
      <div class="field-body">
        <div class="field">
          <div class="control">
            <%= p.submit class: "button is-primary" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
  
  

app/views/users/index.html.erb
<% @users.each do |user| %>
<%= link_to user.username, user %>
<% end %>

app/views/users/new.html.erb
<br>
<br>
<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column"></div>
      <div class="column">
      <% content_tag(:h2, flash[:error], class: "is-error") if flash[:error] %>
      <section class="field is-horizontal">
        <%= form_for @user do |u| %>

          <div class="field">
            <div class="label">
              <%= u.label :username %>
            </div>
            <div class="field-body">
              <div class="field">
                <div class="control">
                  <%= u.text_field :username, class: "input is-focused #{"is-danger" if flash[:username]}" %>
                </div>
              </div>
            </div>
            <%= content_tag(:p, flash[:username], class: "help is-danger") if flash[:username] %>
          </div>

          <div class="field">
            <div class="label">
              <%= u.label :email %>
            </div>
            <div class="field-body">
              <div class="field">
                <div class="control">
                  <%= u.text_field :email, class: "input is-focused #{"is-danger" if flash[:email]}" %>
                </div>
              </div>
            </div>
            <%= content_tag(:p, flash[:email], class: "help is-danger") if flash[:email] %>
          </div>

          <div class="field">
            <div class="label">
              <%= u.label :password %>
            </div>
            <div class="field-body">
              <div class="field">
                <div class="control">
                  <%= u.password_field :password, class: "input is-focused #{"is-danger" if flash[:password]}" %>
                </div>
              </div>
            </div>
            <%= content_tag(:p, flash[:password], class: "help is-danger") if flash[:password] %>
          </div>

          <div class="field">
            <div class="label">
              <%= u.label :password_confirmation %>
            </div>
            <div class="field-body">
              <div class="field">
                <div class="control">
                  <%= u.password_field :password_confirmation, class: "input is-focused #{"is-danger" if flash[:password]}" %>
                </div>
              </div>
            </div>
          </div>
          <div class="field is-horizontal">
            <div class="field-label">
              <!-- Left empty for spacing -->
            </div>
            <div class="field-body">
              <div class="field">
                <div class="control">
                  <%= u.submit class: "button is-primary" %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <div class="column"></div>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<% require 'chartkick' %>
<section class="hero is-medium is-primary is-bold" style="background-image: url('/assets/splash/olympic-lift.jpg')">
  <div class="hero-body">
    <div class="container is-pulled-left">
      <h1 class="title">
        PRO FITNESS
      </h1>
      <h2 class="subtitle is-pulled-left">
        The Importance of being <%= @user.profile.name.titleize %>
      </h2>
    </div>
  </div>
</section>


<section class="section">
  <div class="container">
    <h2 class="is-error"><%= flash[:error] if flash[:error] %></h2>
    <%= form_for Workout.new do |w| %>
      <div class="field has-addons">
        <div class="field has-addons">
          <p class="control has-icons-left has-icons-right">
            <%= w.hidden_field :user_id, value: @user.id %>
            <%= w.number_field :user_weight, class: "input is-focused", placeholder: "Weight"%>
            <span class="icon is-small is-left">
              <i class="fas fa-weight"></i>
            </span>
          </p>
          <p class="control">
            <p class="button is-static"><%= @user.profile.metric == true ? "Kg" : "lbs" %></a>
          </p>
        </div>
        <i>  </i>
        <div class="field">
          <p class="control has-icons-left">
            <%= w.date_field :date, class: "input is-focused #{"is-danger" if flash[:date]}" , value: Time.now.strftime("%Y-%m-%d")%><br>
            <span class="icon is-small is-left">
              <i class="fas fa-calendar-check"></i>
            </span>
          </p>
        </div>
        <p class="control">
          <%= w.submit "Log Workout", class: "button is-primary"%>
        </p>
      </div>
    <% end %>
  </div>
</section>    

<section class="section">
  <div class="container">
    <%= column_chart @data, xtitle: "Days Ago", ytitle: "Weight #{@user.profile.metric == true ? "Kg" : "lbs"}" %>
    <%= form_tag '/users/graph', method: :get do %>
      <%= hidden_field_tag :id, value = @user.id %>
      <div class="field has-addons">
        <div class="control has-icons-left">
          <div class="select">
            <%= select_tag  :exercise_id,
                        options_from_collection_for_select(Exercise.all, "id", "name"),
                        class: "select is-focused is-fullwidth" %>
          </div>
          <span class="icon is-small is-left">
            <i class="fas fa-dumbbell"></i>
          </span>
        </div>
        <div class="control">
          <%= submit_tag "Update Graph", class: "button is-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column"></div>
      <div class="column is-centered">
        <div class="content">
          <h1>Last 5 Workouts</h1>
            <ul id="no-dots">
              <% @user.last_five_workouts.each do |workout| %>
                <li>
                  <h2><%= link_to workout.date.strftime("%A, %b %d"), workout_path(workout) %></h2>
                  <ul>
                    <% workout.workout_sets.each do |set| %>
                      <li>
                        <h5><%= "#{set.exercise.name.capitalize}: #{set.reps} x #{set.weight} #{@user.profile.metric == true ? "Kg" : "lbs"}" %></h5>
                      </li>
                    <% end %>
                  </ul>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
        <div class="column"></div>
      </div>
    </div>
  </div>
</section>

<div class="content" is-large>
  <%= link_to "Check Out Some Exercises", exercises_path %>
</div>