config/routes.rb
Rails.application.routes.draw do
  root 'application#splash'
  get       '/login', to: 'sessions#new'
  post      '/login', to: 'sessions#create'
  delete    '/login', to: 'sessions#destroy', as: '/logout'
  get       '/users/graph', to: 'users#graph'
  get       '/exercises/search', to: 'exercises#search'
  get       '/contact', to: 'pages#contact'
  get       '/about', to: 'pages#about'
  resources :categories
  resources :exercises
  resources :workouts
  resources :workout_sets, only: [:new, :create, :edit, :update, :destroy]
  resources :users, only: [:new, :create, :edit, :update, :show]
  resources :profiles, only: [:show, :new, :create, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProFitness</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': true %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
  </head>

  <body>
    <header>
      <nav class="navbar" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
          <a href="/" id="logo"><%= image_tag "logo/logo-rect.jpg" %></a>
          <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>
        <div id="navbarBasicExample" class="navbar-menu">
          <div class="navbar-end">
            <div class="navbar-item has-dropdown is-hoverable">
              <a class="navbar-link">User</a>
              <div class="navbar-dropdown">
                <% if logged_in? %>
                  <%= link_to "Home", user_path(set_current_user) , class: "navbar-item"%>
                  <hr class="navbar-divider">
                  <%= link_to "Edit Profile", edit_profile_path(set_current_user) , class: "navbar-item"%>
                  <hr class="navbar-divider">
                  <%= link_to "Exercises", exercises_path, class: "navbar-item"%>
                  <hr class="navbar-divider">
                  <%= link_to "Logout", logout_path , method: :delete, class: "navbar-item"%>
                <% else %>
                <%= link_to "Login", login_path, class: "navbar-item"%>
                <hr class="navbar-divider">
                <%= link_to "Sign Up", new_user_path, class: "navbar-item"%>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </nav>
    </header>

    <%= yield %>

  <footer class="footer">
    <div class="content has-text-centered">
      <p>
        <a href="https://github.com/MoreSaltMoreLemon/ProFitness">
          <strong>ProFitness</strong>
        </a> by <a href="https://www.linkedin.com/in/benhaugen88/">Ben Haugen</a> & <a href="https://www.linkedin.com/in/ezra-schwepker/">Ezra Schwepker</a>. Get your lift on!
      </p>
    </div>
  </footer>



</html>